# Site settings
baseURL = "https://bernardogalvao.netlify.app/"
languageCode = "en-us"
title = "Portfolio website for Bernardo Galvão"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Bernardo Galvão"
  description = "Your description"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Portfolio Website"
    subtitle = "LBS MFA2021"
    # Optional logo as brand stored in img/
    # logo = "logo.png"
    
    [[params.navigation.links]]
    name = "Home"
    url = "#"

  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Hi, my name is Bernardo Galvão"
    subtitle = "THIS MY PORTFOLIO WEBSITE."
    buttonText = "FIND OUT MORE ABOUT WHAT I HAVE DONE"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "Yield Curve Inversion"
      subtitle = "What is the relation between Yield Curve and Recession at the USA"
      image = "Pic12.jpeg"
      url = "blogs/blog1"

    [[params.tiles.showcase]]
      title = "2016 California Contributors plots"
      subtitle = "Top 10 cities in highest amounts raised in political contributions in California during the 2016 US Presidential election."
      image = "Dollar.jpg"
      url = "blogs/blog2"

    [[params.tiles.showcase]]
      title = "Excess rentals in TfL bike sharing"
      subtitle = "The impact of Covid-19 on Boris Bike."
      image = "Boris.jpg"
      url = "blogs/blog3"

    [[params.tiles.showcase]]
      title = "Donald Trump's Approval"
      subtitle = "Has COVID-19 affected Trump's approval?"
      image = "pic40.jpg"
      url = "blogs/blog4"

    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "About Me!"
    subtitle = """My name is Bernardo Galvão and I was born in a city called Nova Friburgo in the countryside of the State of Rio de Janeiro.
    I graduated in Production Engineering at Universidade Federal Fluminense and my final thesis was an application of the Modern Portfolio Theory on the Brazilian Market of pension funds with the addition of IVVB11, a Brazilian ETF with exposure to S&P500, to analyze the diversification’s impact.
    Over the past few years, I have worked in different companies and roles. I worked at L'Oréal Brazil, then I became Summer Intern at Banco Safra, one of the biggest Investment Banks in Brazil.
    My most recent work was as Offshore Investment Intern at Turim MFO, brazilian biggest independet Multi-Family Office.
    I won the 1st Turim national award organized by Turim MFO: Crack an economic case by creating an Inflation Index for UHNW. I was awarded 9 meetings with Asset management in London.
    I decided took the CFA level 1 in December of 2019 and I took GMAT and IELTS in February of 2020 and September of 2019, respectively.
    My goal is to achieve a very important role in the **Investment Banking industry**.If you would like to know more about me you can check my LinkedIn at the bottom of the site."""
    buttonText = "Get Started"
    url = "blogs"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    # formEmail = "example@domain.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "bernardod.mfa2021@london.edu"

    [[params.contact.phone]]
    title = "Phone"
    phone = "(44) 7309-190369"

    [[params.contact.address]]
    title = "Address"
    street = "Regent's Park"
    city = "London, NW1 4SA"
    country = "United Kingdom"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Company Name"

    # Uses font awesome icons
    [[params.footer.social]]
      icon = "fa-instagram"
      url= "https://www.instagram.com/galvaobe"
      label = "Instagram"
    
    [[params.footer.social]]
      icon = "fa-github"
      url= "https://github.com/BernardoGalvao"
      label = "GitHub"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/in/bernardo-galvao/"
      label = "LinkedIn"

    [[params.footer.quicklinks]]
      text = "Design: "
      url= "https://www.html5up.net"
      alt = "HTML5 UP"
